# Generated by Django 3.0.8 on 2020-08-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_booklist_borrowed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booklist',
            options={'verbose_name_plural': 'BookList'},
        ),
        migrations.AddField(
            model_name='booklist',
            name='book_image',
            field=models.ImageField(blank=True, default='img.jpg', null=True, upload_to='pics'),
        ),
    ]
