# Generated by Django 3.0.8 on 2020-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={},
        ),
        migrations.AddField(
            model_name='credentials',
            name='image',
            field=models.ImageField(blank=True, default='img.txt', upload_to=''),
        ),
    ]
