# Generated by Django 3.0.8 on 2020-08-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_auto_20200804_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name_plural': 'credentials'},
        ),
        migrations.RemoveField(
            model_name='credentials',
            name='image',
        ),
    ]
