# Generated by Django 3.0.8 on 2020-08-12 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_auto_20200806_2049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credentials',
        ),
    ]
